# A list of features (kernel patches) to use
kernel_features:
  - 'strip'
  - 'base'
  - "{{'host-gentoo' if ansible_facts['os_family'] == 'Gentoo'}}"
  - "{{'host-x86_64' if ansible_facts['architecture'] == 'x86_64'}}"
  - "{{'host-amd' if 'AuthenticAMD' in ansible_facts['processor']}}"
  - "{{'host-H12SSL' if ansible_facts['board_name'] == 'H12SSL-C'}}"
  - "{{'host-sabertooth990fx' if ansible_facts['board_name'] == 'SABERTOOTH 990FX'}}"
  - 'fs-basic'
  - 'net-netfilter'
  - "{{'virt-docker' if 'docker' in services}}"
  - "{{'storage-crypt' if encrypted_root}}"
# Features
# base: Includes basic additions to the kernel
# strip: removes many unnecessary features that may be part of defconfig
# network: adds basic network support, full featured netfilter
# kspp: Kernel self protection project configs
# virt: Virtualization (kvm and qemu support)
# docker: adds docker support
# initramfs: adds initramfs support
# fs-linux: adds btrfs and ext4
# fs-msdos: adds fat
# net-basic: adds bridging and vlan support
# Init custom features
cust_kernel_features: []

# Set late features
late_kernel_features:
  - "{{'selinux' if 'selinux' in features}}"
  - "{{'kspp' if gentoo_hardened}}"

# Defines whether or not make clean is ran before make
build_clean: false

# Defines whether or not to run make allnoconfig
kconfig_allnoconfig: false
