- name: Install opensshd
  become: yes
  package:
    name: net-misc/openssh
    state: present


- name: configure /etc/ssh/sshd_config
  become: yes
  template:
    backup: true
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: u=rw,g=,o=
    validate: sshd -t -f %s
