- name: Install the kernel
  hosts: gentoo_servers
  serial: 1
  tasks:
    - name: Import the gentoo role and install the kernel
      import_role:
        name: gentoo
        tasks_from: configure_kernel
