- name: test
  hosts: servers
  tasks:
    - include_vars:
        file: users.yaml
    - name: aaa
      debug:
        var: item
      with_items: "{{users | selectattr('groups', 'defined')}}"

    #  - import_role:
    #    name: gentoo
    #    tasks_from: check_system.yaml
