- name: test
  hosts: servers
  tasks:
    - debug:
        msg: "{{netconfig.keys()}}"
    - debug:
        msg: "{{dhcp_interfaces | regex_replace('\\.', '_')}}"
    - debug:
        msg: "{{netconfig.keys() | difference(dhcp_interfaces | regex_replace('\\.', '_'))}}"
    - debug:
        msg: "{{dhcp_interfaces | regex_replace('\\.', '_') | difference(netconfig.keys())}}"
    - debug:
        msg: "{{b}}"
      when: (dhcp_interfaces | regex_replace('\\.', '_')) is subset(netconfig.keys())
      vars:
        a: ['fib_lan']
        b: "{{dhcp_interfaces | regex_replace('\\.', '_')}}"

