- name: Run gentoo role
  hosts: servers
  serial: 1
  tasks:
    - import_role:
        name: gentoo
        tasks_from: configure_kernel
    - import_role:
        name: gentoo
        tasks_from: configure_bootloader
#    - import_role:
#        name: service_dhcp
