- name: "Configure: install sshd"
  become: yes
  package:
    name: "{{emerge_ssh_full}}"
    state: present
- name: "Configure: copy ssh config"
  become: yes
  template:
    backup: true
    src: "sshd_config"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: u=rw,g=,o=
    validate: sshd -t -f %s
