# Remove most of the ssh args to make the connection simpler, mostly gets rid of the cached connection sockets
ansible_ssh_args: ""

# Define the default services
services: ['ssh']

# Define whether or not to configure for selinux
selinux_configure: false

# Define the default gentoo sources arch  
emerge_arch: "amd64"

# Define the SSH package name
emerge_ssh_full: "net-misc/openssh"

# Define the sudo package name
emerge_sudo_full: "app-admin/sudo"

# Define the bootloader
emerge_bootloader: "grub"
