- name: Check gentoo
  fail:
    msg: "Error: Using the Gentoo server role on a server that is not reporting using {{ansible_facts['os_family']}}"
  when: ansible_facts['os_family'] != 'Gentoo'

- debug:
    var: ansible_facts['mounts']

- name: Check chroot
  include_role:
    name: gentoo
    tasks_from: loop_drive_check.yaml
  with_items: "{{ansible_facts['device_links']['ids'] | dict2items}}"
  loop_control:
    loop_var: drive_match
  when: root_device in drive_match.value
