- name: Configuring sudo
  become: yes
  block:
    - name: Install sudo
      portage:
        package: app-admin/sudo
        state: present
    - name: Install /etc/sudoers.conf
      copy:
        backup: yes
        src: etc/sudoers.conf
        dest: /etc/sudoers.conf
        owner: root
        group: root
        mode: u=r,g=r,o=
    - name: Create /etc/sudoers.d
      file:
        path: /etc/sudoers.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=x
    - name: Install /etc/sudoers.d/99-ansible
      template:
        src: etc/sudoers.d/99-ansible
        dest: /etc/sudoers.d/99-ansible
        owner: root
        group: root
        mode: u=r,g=r,o=

- name: Configure pam_ssh_agent_auth
  become: yes
  block:
    - name: Set package.accept_keywords for pam_ssh_agent_auth
      copy:
        src: etc/portage/package.accept_keywords/pam_ssh_agent_auth
        dest: /etc/portage/package.accept_keywords/pam_ssh_agent_auth
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Install pam_ssh_agent_auth
      package: 
        name: sys-auth/pam_ssh_agent_auth
        state: present

    - lineinfile:
        path: /etc/pam.d/sudo
        state: present
        line: "auth sufficient pam_ssh_agent_auth.so file=/etc/ssh/sudo_authorized_keys"
        insertbefore: '^auth\s+(substack|include)\s+system-auth$'
    - lineinfile:
        path: /etc/pam.d/sudo
        state: present
        line: "auth include system-auth"
        regexp: '^auth\s+(substack|include)\s+system-auth$'
    - lineinfile:
        path: /etc/pam.d/sudo
        state: present
        line: "account include system-auth"
        regexp: '^account\s+(substack|include)\s+system-auth$'
    - lineinfile:
        path: /etc/pam.d/sudo
        state: present
        line: "session include system-auth"
        regexp: '^session\s+(substack|include)\s+system-auth$'
    - file:
        state: directory
        path: /etc/ssh/
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx
    - file:
        state: touch
        path: /etc/ssh/sudo_authorized_keys
        owner: root
        group: root
        mode: u=rw,g=,o=
    - name: Add SSH keys
      include_role:
        name: service_ssh
        tasks_from: loop_sudo_keys.yaml
      with_items: "{{users | dict2items}}"
      loop_control:
        loop_var: user
      when: "'wheel' in user.value.get('groups') and 'ssh_keys' in user.value"

