- name: Configure the chroot environment
  include_role:
    name: gentoo
    tasks_from: configure_chroot
  when: use_chroot

- name: Configuring the base system
  include_role:
    name: gentoo
    tasks_from: configure_base

- name: Configure SELinux
  include_role:
    name: gentoo_selinux
  when: "'selinux' in features"

- name: Configuring services
  include_role:
    name: "service_{{item}}"
  loop: "{{services}}"
  when: services is defined

- name: Disable netmount
  become: yes
  service:
    name: netmount
    state: stopped
    enabled: false
  when: services is defined and 'netmount' not in services
