- name: Installing /etc/conf.d/hostname
  become: yes
  template:
    backup: yes
    src: etc/conf.d/hostname
    dest: /etc/conf.d/hostname
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    # the %s is required, source can't be run from subprocess
    # this could break if the template file is broken
    validate: "echo %s >> /dev/null && hostname {{inventory_hostname}}"

