- name: Configure udev rules for networking
  become: yes
  block:
    - name: Installing /etc/udev/rules.d/99-ansible-net.rules
      template:
        src: etc/udev/rules.d/99-ansible-net.rules
        dest: /etc/udev/rules.d/99-ansible-net.rules
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Get current ip link information
      command: ip link
      register: ip_info
    - name: Rename network interfaces
      command: "bash -c 'ip link set dev {{interface_match.0.device}} down && ip link set {{interface_match.0.device}} name {{item.key}}'"
      loop: "{{netconfig | dict2items}}"
      vars:
        # Extracts interfaces from ansible_facts using the interfaces field
        # Then filters out ones which have mac addresses
        host_interfaces: "{{ansible_facts.interfaces | map('extract', ansible_facts) | selectattr('macaddress', 'defined')}}"
        # Combine the detection logic with some data manipulation
        # Selects the host interface that has the mac associated with the interface used in this current iteration
        interface_match: "{{host_interfaces | selectattr('macaddress', '==', item.value.mac) if item.value.mac is defined}}"
      when: interface_match and netconfig[interface_match.0.device] is not defined and item.key not in ip_info.stdout
    - name: Add interface init scripts
      file:
        state: "link"
        src: /etc/init.d/net.lo
        dest: "/etc/init.d/net.{{item.key}}"
      loop: "{{netconfig | dict2items}}"
      when: item.value.mac is defined
    - name: Check for invalid netifrc init scripts
      find:
        paths: /etc/init.d/
        patterns: "net.*"
        file_type: "link"
      register: netifrc_inits
    - name: Checking for invalid interfaces
      set_fact:
        invalid_interfaces: "{{[item.path] | union(invalid_interfaces | select)}}"
      with_items: "{{netifrc_inits.files}}"
      vars:
        interface_name: "{{item.path | regex_replace('^.*/net\\.(.*)', '\\1')}}"
        invalid_interfaces: []
      when: "interface_name in netconfig and netconfig[interface_name].mac is not defined and netconfig[interface_name].bridge is not defined"
    - name: Deleting invalid interface init scripts
      file:
        path: "{{item}}"
        state: absent
      with_items: "{{invalid_interfaces}}"
      when: invalid_interfaces is defined and clean_net
    - name: Update /etc/conf.d/net
      template:
        backup: yes
        src: etc/conf.d/net
        dest: /etc/conf.d/net
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Start network interfaces
      service:
        name: "net.{{item.key}}"
        state: restarted
        enabled: true
        runlevel: default
      loop: "{{netconfig | dict2items}}"
      when: item.value.autostart is defined and item.value.autostart
