- name: jump check_system
  include_role:
    name: gentoo
    tasks_from: check_system

- name: Jump configure_system
  include_role:
    name: gentoo
    tasks_from: configure_system
  when: autorun
