- name: Include kernel vars
  include_defaults:
    name: kernel

- name: Build kernel
  become: yes
  block:
    - name: "Kernel: Configure gentoo-kernel use"
      template:
        backup: yes
        src: "gentoo-kernel_use"
        dest: "/etc/portage/package.use/gentoo-kernel"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: "Kernel: Configure gentoo-kernel accept-keywords"
      template:
        backup: yes
        src: "gentoo-kernel_accept_keywords"
        dest: "/etc/portage/package.accept_keywords/gentoo-kernel"
        owner: root
        group: root
    - name: "Kernel: emerge"
      package:
        name: "{{emerge_kernel_full}}"
        state: present

