- name: Configure SELinux
  include_role:
    name: gentoo_selinux
    tasks_from: configure

- name: Configure users
  include_role:
    name: gentoo_selinux
    tasks_from: configure_users

- name: Relabel system
  include_role:
    name: gentoo_selinux
    tasks_from: relabel
  when: selinux_relabel
