- name: Configuring sudo
  become: yes
  block:
    - name: Install sudo
      emerge:
        package: "{{emerge_sudo_full}}"
        state: present
    - name: Install /etc/sudoers.conf
      copy:
        backup: yes
        src: etc/sudoers.conf
        dest: /etc/sudoers.conf
        owner: root
        group: root
        mode: u=r,g=r,o=
    - name: Create /etc/sudoers.d
      file:
        path: /etc/sudoers.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=x
    - name: Install /etc/sudoers.d/selinux
      copy:
        backup: yes
        src: etc/sudoers.d/selinux
        dest: /etc/sudoers.d/selinux
        owner: root
        group: root
        mode: u=r,g=r,o=
    - name: Install /etc/sudoers.d/wheel
      copy:
        backup: yes
        src: etc/sudoers.d/wheel
        dest: /etc/sudoers.d/wheel
        owner: root
        group: root

