- name: Configure the bootloader to use GRUB
  become: yes
  block:
    - set_fact:
        has_efi_conf: false
    - set_fact:
        efi_file: '\EFI\BOOT\BOOTX64.EFI'
    - set_fact:
        efi_file: '\EFI\gentoo\grubx64.efi'
      when: emerge_kernel == 'gentoo-kernel'
    - name: Check bootloader status
      become: yes
      block:
        - name: Get efibootmgr configuration
          command: efibootmgr
          register: efibootmr_output
        - name: Get the boot partition UUID
          command: "lsblk /dev/disk/by-id/{{boot_device}}-part1 -n -o PARTUUID"
          register: partition_uuid
        - name: Check efibootmgr configuration
          set_fact:
            has_efi_conf: true
          when: partition_uuid.stdout_lines[0] in item and "File({{efi_file}})" in item
          with_items: "{{efibootmr_output.stdout_lines}}"

    - name: Configure bootloader entry
      become: yes
      command: "efibootmgr -c -l '{{efi_file}}' -L 'ansible-grub' -d /dev/disk/by-partuuid/{{partition_uuid.stdout_lines[0]}}"
      when: not has_efi_conf
