- name: Configuring grub package
  become: yes
  block:
    - name: Install grub package
      portage:
        package: sys-boot/grub
        state: present
    - name: Install /etc/default/grub
      template:
        backup: yes
        src: etc/default/grub
        dest: /etc/default/grub
        owner: root
        group: root
        mode: u=rw,g=r,o=r

- name: Mount /boot
  become: yes
  block:
    - name: Check /boot mount
      command: mount
      register: result
    - name: Mount /boot
      command: mount /boot
      when: "'on /boot type' not in result['stdout']"

- name: Installing grub bootloader
  become: yes
  block:
    - name: Create the EFI directory
      file:
        path: /boot/efi
        state: directory
        owner: root
        group: root
    - name: Install GRUB to the EFI partition
      command: grub-install --efi-directory=/boot/efi
