# Configures the kernel based on the specified parameters

- name: Configure package.accept_keywords
  become: yes
  template:
    backup: yes
    src: "etc/portage/package.accept_keywords/{{item}}"
    dest: "/etc/portage/package.accept_keywords/{{item}}"
    owner: root
    group: root
  loop: ['gentoo-kernel', 'gentoo-sources', 'installkernel-gentoo']
- name: Configure package.use
  become: yes
  template:
    backup: yes
    src: "etc/portage/package.use/{{item}}"
    dest: "/etc/portage/package.use/{{item}}"
    owner: root
    group: root
  loop: ['gentoo-kernel', 'gentoo-sources', 'installkernel-gentoo']

- name: conditional install gentoo-kernel
  include_role:
    name: gentoo
    tasks_from: install_gentoo_kernel
  when: emerge_kernel == 'gentoo-kernel'

- name: conditional install gentoo-sources
  include_role:
    name: gentoo
    tasks_from: install_gentoo_sources
  when: emerge_kernel == 'gentoo-sources'

