- name: Enabling OpenRC logging
  become: yes
  lineinfile:
    backup: yes
    path: /etc/rc.conf
    line: 'rc_logger="YES"'
    insertafter: '#rc_logger="NO"'
    owner: root
    group: root
    mode: u=rw,g=r,o=r

