- name: Check Grub
  - name: Check use env flag
    fail:
      msg: emerge_bootloader is not set to grub
    when: emerge_bootloader != 'grub'

- name: Configuring grub base
  become: yes
  block:
    - name: Install grub package
      portage:
        package: sys-boot/grub
        state: present
    - name: Install /etc/default/grub
      template:
        backup: yes
        src: etc/default/grub
        dest: /etc/default/grub
        owner: root
        group: root
        mode: u=rw,g=r,o=r
