- name: Configuring the base system
  include_role:
    name: gentoo
    tasks_from: configure_base

- name: Configure SELinux
  include_role:
    name: gentoo_selinux
  when: selinux_configure

- name: Configuring services
  include_role:
    name: "service_{{item}}"
  loop: "{{services}}"
  when: services is defined

