- name: Configuring sudo
  become: yes
  block:
    - name: Install sudo
      portage:
        package: app-admin/sudo
        state: present
    - name: Install /etc/sudoers.conf
      copy:
        backup: yes
        src: etc/sudoers.conf
        dest: /etc/sudoers.conf
        owner: root
        group: root
        mode: u=r,g=r,o=
    - name: Create /etc/sudoers.d
      file:
        path: /etc/sudoers.d
        state: directory
        owner: root
        group: root
        mode: u=rwx,g=rx,o=x
    - name: Install /etc/sudoers.d/99-ansible
      template:
        backup: yes
        src: etc/sudoers.d/99-ansible
        dest: /etc/sudoers.d/99-ansible
        owner: root
        group: root
        mode: u=r,g=r,o=

