- name: Check boot device
  block:
    - name: Check that the boot device is set
      fail:
        msg: "valid boot_device is not set: {{boot_device}}"
      when: boot_device not in ansible_facts['device_links']['ids'].values() | flatten

- name: Configuring grub package
  become: yes
  block:
    - name: Install grub package
      portage:
        package: sys-boot/grub
        state: present
    - name: Install /etc/default/grub
      template:
        backup: yes
        src: etc/default/grub
        dest: /etc/default/grub
        owner: root
        group: root
        mode: u=rw,g=r,o=r

- name: Mount /boot
  become: yes
  block:
    - name: Check /boot mount
      command: mount
      register: result
    - name: Mount /boot
      command: mount /boot
      when: "'on /boot type' not in result['stdout']"

- set_fact:
    grub_installed: false

- set_fact:
    efi_file_loc: '/boot/EFI/BOOT/BOOTX64.EFI'
- set_fact:
    efi_file_loc: '/boot/EFI/gentoo/grubx64.efi'
  when: emerge_kernel == 'gentoo-kernel'

- name: Check grub install
  block:
    - name: Get removable EFI file info
      stat:
        path: "{{efi_file_loc}}"
      register: efi_file
    - name: Get grub EFI file info
      stat:
        path: /boot/grub/x86_64-efi/grub.efi
      register: grub_file
    - name: Get font info
      stat:
        path: /boot/grub/fonts/unicode.pf2
      register: font_file
    - name: Check grub
      set_fact:
        grub_installed: true
      when: font_file.stat.exists and grub_file.stat.exists and efi_file.stat.exists

- name: Installing grub bootloader
  become: yes
  block:
    - name: Create the EFI directory
      file:
        path: /boot/efi
        state: directory
        owner: root
        group: root
    - name: Install removable GRUB to the EFI partition
      command: grub-install --efi-directory=/boot/ --removable
      when: emerge_kernel == 'gentoo-sources'
    - name: Install GRUB to the EFI partition
      command: grub-install --efi-directory=/boot/
      when: emerge_kernel == 'gentoo-kernel'
  when: grub_installed is defined and not grub_installed
