# Configures emerge package.use and package.accept_keywords to install gentoo-kernel
- name: Install
  become: yes
  block:
    - name: Install /etc/portage/package.use/gentoo-kernel
      template:
        backup: yes
        src: etc/portage/package.use/gentoo-kernel
        dest: /etc/portage/package.use/gentoo-kernel
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Install /etc/portage/package.accept_keywords/gentoo-kernel
      template:
        backup: yes
        src: etc/portage/package.accept_keywords/gentoo-kernel
        dest: /etc/portage/package.accept_keywords/gentoo-kernel
        owner: root
        group: root
    - name: emerge gentoo-kernel
      package:
        name: "{{emerge_kernel_full}}"
        state: present

