# Configures emerge package.use and package.accept_keywords to install gentoo-sources
- name: Obtain, prepare, and configure gentoo sources
  become: yes
  block:
    - name: emerge gentoo-sources
      portage:
        package: sys-kernel/gentoo-sources
        state: present
        changed_use: true
    - name: emerge dracut
      portage:
        package: sys-kernel/dracut
        state: present
      when: use_initramfs
    - name: Configure and compile sources
      include_role:
        name: kernel_configurator
