# Configures emerge package.use and package.accept_keywords to install gentoo-sources
- name: Obtain, prepare, and configure gentoo sources
  become: yes
  block:
    - name: emerge gentoo-sources
      portage:
        package: gentoo-sources
        state: present
        changed_use: true
    - name: Configure and compile sources
      include_role:
        name: kernel_configurator
    - name: Install grub config
      command: grub-mkconfig -o /boot/grub/grub.cfg
