- name: Install
  become: yes
  block:
    - name: Configure gentoo-kernel use
      template:
        backup: yes
        src: "use"
        dest: "/etc/portage/package.use/gentoo-kernel"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Configure gentoo-kernel accept-keywords
      template:
        backup: yes
        src: "accept_keywords"
        dest: "/etc/portage/package.accept_keywords/gentoo-kernel"
        owner: root
        group: root
    - name: emerge gentoo-kernel
      package:
        name: "{{emerge_kernel_full}}"
        state: present

