# Define the default services
services: ['ssh']

# Define the empty features list
features: []

# Define whether or not to used the hardened profile
gentoo_hardened: true

# Define the gentoo profile
# Hardened and selinux will be added
emerge_profile: "default/linux/amd64/17.1"

# Define the SSH package name
emerge_ssh_full: "net-misc/openssh"

# Define the kernel package
# gentoo-kernel for sys-kernel/gentoo-kernel, maintained by fedora/gentoo
# gentoo-sources for sys-kernel/gentoo-sources,  requires patches to be specified
emerge_kernel: "gentoo-sources"
# Whether or not to use the unstable kernel
emerge_kernel_unstable: false
# Kernel arch
emerge_kernel_arch: "amd64"
# Define whether or not to use an initramfs, may be overridden by tasks
use_initramfs: "{{encrypted_root}}"

# Set whether or not to autorun this script
autorun: false

# Don't reformat partitions unless specified
reformat_boot: false
reformat_root: false
# Set the default root partition number
root_partition: 1
# Set the bootloader partition size
boot_partition_size: 512

# the serial port ID (/dev/tty{n})
serial_port: "S1"
# Set the system root location
system_root: "/"
# Whether or not the root partition should be encrypted
encrypted_root: false
# Whether or not to compile EFI stub support into the kernel, and use it with efibootmgr
efi_stub: false

# When true, network init files will be deleted if not present in the config
clean_net: false

# When true, does a chroot install, dangerous to set manually
use_chroot: false

