- name: Clean the build directory
  become: yes
  command: make clean
  args:
    chdir: /usr/src/linux
  when: build_clean

- name: Build kernel sources
  become: yes
  command: "make -j {{ansible_facts['processor_vcpus'] + 1}}"
  args:
    chdir: /usr/src/linux

- name: Install the kernel, modules, and heders
  become: yes
  block:
    - name: Check if modules are enabled
      command: "grep 'CONFIG_MODULES=y' /usr/src/linux/.config -q"
    - name: Install modules
      command: make modules_install
      args:
        chdir: /usr/src/linux
  always:
    - name: Install the headers
      command: make headers_install
      args:
        chdir: /usr/src/linux
    - name: Install the kernel
      command: make install
      args:
        chdir: /usr/src/linux

