- name: Bootstrap selinux base
  become: yes
  command: emerge -1 -n selinux-base
  environment:
    FEATURES: "-selinux"

- name: Configure SELinux
  become: yes
  template:
    src: etc/selinux/config
    dest: /etc/selinux/config
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Emerge SELinux
  become: yes
  block:
  - name: Emerge base
    command: "emerge -1 selinux-base"
    environment:
      FEATURES: "-selinux -sesandbox"
  - name: Emerge base policy
    command: "emerge -1 selinux-base-policy"
    environment:
      FEATURES: "-selinux -sesandbox"
  - name: Rebuild @world
    portage:
      package: '@world'
      changed_use: true
      deep: true
      update: true

- name: Create SELinux mounts
  become: yes
  block:
  - name: Make SELinux tmp mount
    mount:
      src: tmpfs
      path: /tmp
      fstype: tmpfs
      opts: 'defaults,noexec,nosuid,rootcontext=system_u:object_r:tmp_t'
      state: present
  - name: Make SELinux run mount
    mount:
      src: tmpfs
      path: /run
      fstype: tmpfs
      opts: 'mode=0755,nosuid,nodev,rootcontext=system_u:object_r:var_run_t'
      state: present
