- name: Check status
  tags: status
  ansible.builtin.service_facts:



- name: Print running services
  tags: status
  debug:
    msg: "{{ ansible_facts.services[item].state }}"
  when: ansible_facts.services[item].state == "running"
  with_items: "{{ ansible_facts.services }}"
