- set_fact:
    configs_differ: false

- name: Check build differences
  block:
    - name: Check existing kernel config
      stat:
        path: "/boot/config-{{ansible_facts['kernel']}}"
      register: running_config
    - name: Check new kernel config
      stat:
        path: "/usr/src/linux/.config"
      register: new_config
    - name: Compare configs
      set_fact:
        configs_differ: true
      when: "'checksum' not in running_config.stat or running_config.stat.checksum != new_config.stat.checksum"

- name: Build the kernel
  become: yes
  block:
    - name: Clean the build directory
      command: make clean
      args:
        chdir: /usr/src/linux
      when: build_clean
    - name: Build kernel sources
      command: "make -j {{ansible_facts['processor_vcpus'] + 1}}"
      args:
        chdir: /usr/src/linux
    - name: jump install_kernel
      include_role:
        name: kernel_configurator
        tasks_from: install_kernel
  when: configs_differ

